/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Auxiliares.Par;
import Dominio.Partida;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author santiago_soto_laptop
 */
public final class AuxMovsPosibles extends javax.swing.JFrame {

    public ArrayList<Par[]> movsPosibles;
    private final VentanaJugar ventJugar;
    private final Partida partida;

    public AuxMovsPosibles(Partida unaPartida, VentanaJugar vent) {

        ventJugar = vent;
        partida = unaPartida;
        initComponents();
        actualizar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        int a = this.jList1.getSelectedIndex();


    }//GEN-LAST:event_jList1ValueChanged

    /**
     */
    public void actualizar() {
        partida.getTablero().deleteObserver(ventJugar);
        movsPosibles = partida.getTablero().movimientosPosibles(partida);
        partida.getTablero().addObserver(ventJugar);

        this.jList1.removeAll();
        DefaultListModel m = new DefaultListModel();
        for (int i = 0; i < movsPosibles.size(); i++) {
            m.addElement(Arrays.toString(movsPosibles.get(i)));
        }

        this.jList1.setModel(m);

        ventJugar.update();

    }

   
    public Partida getPartida() {
        return partida;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
