/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Image;
import java.net.MalformedURLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Santiago Soto 219266
 */
public class VentanaCambiarFichas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCambiarFichas
     *
     * @param vent
     */
    public VentanaCambiarFichas(VentanaJugar vent) {
        initComponents();
        this.setLocationRelativeTo(vent);
        this.setVisible(true);
        this.ventanaJugar = vent;
    }

    /**
     * Creates new form VentanaJugarSolitario
     *
     * @param vent
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRojas = new javax.swing.JButton();
        btnAzules = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(200, 231, 221));

        btnRojas.setText("CAMBIAR ROJAS");
        btnRojas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRojasActionPerformed(evt);
            }
        });

        btnAzules.setText("CAMBIAR AZULES");
        btnAzules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzulesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAMBIO DE FICHAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnRojas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAzules)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRojas)
                    .addComponent(btnAzules))
                .addGap(77, 77, 77))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRojasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRojasActionPerformed
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtroImagen = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        fc.setFileFilter(filtroImagen);
        fc.setAcceptAllFileFilterUsed(false);
        int resp = fc.showOpenDialog(this);

        if (resp == JFileChooser.APPROVE_OPTION) {
            try {
                ImageIcon img = new ImageIcon(fc.getSelectedFile().toURL());
                Image image = img.getImage();
                Image newimg = image.getScaledInstance(65, 65, java.awt.Image.SCALE_SMOOTH);
                img = new ImageIcon(newimg);

                ventanaJugar.iconoFichasRojas = img;
                ventanaJugar.update();

            } catch (MalformedURLException ex) {

            }
        }


    }//GEN-LAST:event_btnRojasActionPerformed

    private void btnAzulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzulesActionPerformed
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtroImagen = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        fc.setFileFilter(filtroImagen);
        fc.setAcceptAllFileFilterUsed(false);
        int resp = fc.showOpenDialog(this);

        if (resp == JFileChooser.APPROVE_OPTION) {
            try {
                ImageIcon img = new ImageIcon(fc.getSelectedFile().toURL());
                Image image = img.getImage();
                Image newimg = image.getScaledInstance(65, 65, java.awt.Image.SCALE_SMOOTH);
                img = new ImageIcon(newimg);

                ventanaJugar.iconoFichasAzules = img;
                ventanaJugar.update();

            } catch (MalformedURLException ex) {

            }
        }
    }//GEN-LAST:event_btnAzulesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzules;
    private javax.swing.JButton btnRojas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private VentanaJugar ventanaJugar;
}
